/* _build_app3d.cjs — inline the 3D technique view into index.html.

   WHY A BUILD STEP AT ALL
   index.html is a single-file PWA: everything inline, no <script src>, no network, no backend. So the
   3D modules have to become text inside that one file. The alternative — hand-copying them in — would
   create a second, divergent copy of _s3d_core.js, and _s3d_core.js is shared with the node audit
   (require() loads the same file). A fork would mean the audit could pass on code the app does not
   run, which is the worst possible outcome for a numeric check.

   So this copies the sources VERBATIM between markers, and then verifies by reading the result back
   that each source really is present byte-for-byte. It does not merge, transform or minify anything.

   WHY THE PAYLOAD GOES INSIDE THE APP'S OWN <script> AND NOT ITS OWN
   The first version of this builder wrapped the payload in a second <script> tag, on the reasoning
   that it kept the change away from the app's own script. That reasoning was wrong, and the app's
   regression gate caught it: four suites read index.html with
       /<script>([\s\S]*)<\/script>\s*<\/body>/
   and reported "FAIL: no script block". The app has exactly ONE inline script block, and everything
   from scripts to audits depends on that shape. So the payload is spliced in just before that
   block's closing </script>, and the markers are JS comments so that nothing sits between </script>
   and </body>. The gate's own regex is now asserted below, so a future format change cannot break it
   silently again.

   Idempotent: running it twice produces the same file. The region between the markers is replaced
   wholesale, so hand edits inside that region are deliberately impossible to preserve — edit the
   source modules instead. Everything outside the markers is never touched.
*/
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const HERE = __dirname;
const TARGET = path.join(HERE, 'index.html');

/* Markers are JS comments: they live INSIDE the app's script, so the document still ends
   `</script>\n</body>` exactly as the gate expects. */
const BEGIN = '/* ===== FORGE-3D BEGIN (generated by _build_app3d.cjs — do not edit this region by hand) ===== */';
const END = '/* ===== FORGE-3D END ===== */';

/* The legacy markers from the first version, which wrapped the payload in its own <script> tag.
   Recognised only so this builder can clean up after its earlier self. */
const OLD_BEGIN = '<!-- FORGE-3D BEGIN';
const OLD_END = '<!-- FORGE-3D END -->';

/* Order matters: each module expects the previous one to have run.

   The CLIP files are optional. Each clip registers itself, `_s3d_clips_measured.js` reports any that
   are absent, and the app refuses to offer an exercise whose measured clip did not arrive (the guard
   in `_s3d_app.js` requires a clip to record its measured targets). So a partial clip set is a
   working build that simply offers 3D for fewer exercises — which is strictly better than aborting,
   because an abort here only tempts someone into stubbing a clip, and a stub is exactly the
   fabrication this whole pipeline exists to prevent. A missing CORE module still aborts. */
const REQUIRED = ['_s3d_core.js', '_s3d_render.js', '_s3d_clips_measured.js', '_s3d_props.js', '_s3d_app.js'];
const CLIPS = ['_s3d_clip_squat.js', '_s3d_clip_press.js', '_s3d_clip_legext.js', '_s3d_clip_machinepress.js'];
const MODULES = [REQUIRED[0], REQUIRED[1], ...CLIPS, ...REQUIRED.slice(2)];

/* Clips deliberately NOT inlined, each with the reason it is held back. A defective clip is worse
   than a missing one: the app would render it under the "3D MEASURED" badge with a real source and
   licence underneath, so a visibly wrong movement would be presented as measured. `has3D` returns
   false for a held-back clip, the exercise falls back to its 2D demo, and nothing claims a
   measurement that failed its check.

   EMPTY, and that is a VERIFIED state rather than an assumption: all four clips pass the independent
   re-derivation in `_check_clips_all.cjs` (47 assertions, 0 failed), which recomputes every angle
   from the posed skeleton instead of reading the clip's own record. The press clip sat here while its
   racked elbow measured 9.1 deg — the forearm folded back onto the upper arm rather than a rack — and
   its grip was 11 units (~16 cm) where the reference bar invariant is 0.471 m. It was re-authored to
   a 78.3 deg rack and a 28-unit grip, and this entry was deleted only after that check passed.

   Keep this table even while empty: it is how a bad clip is stopped from reaching the app without
   also stopping the good ones. */
const EXCLUDED = {};

let problems = [];
const skipped = [];
function must(cond, msg) { if (!cond) problems.push(msg); return cond; }

/* --- read and sanity-check the sources ------------------------------------------------- */
const sources = [];
for (const name of MODULES) {
  const p = path.join(HERE, name);
  if (EXCLUDED[name]) {
    skipped.push(name);
    console.warn(`  HELD BACK: ${name}\n             ${EXCLUDED[name]}`);
    continue;
  }
  if (!fs.existsSync(p)) {
    if (CLIPS.indexOf(name) >= 0) {
      skipped.push(name);
      console.warn(`  note: ${name} is not here yet — building without it; that exercise will not offer 3D`);
    } else {
      problems.push(`MISSING SOURCE: ${name} (a core module — the build cannot proceed without it)`);
    }
    continue;
  }
  const text = fs.readFileSync(p, 'utf8');
  must(text.length > 0, `EMPTY SOURCE: ${name}`);
  // A literal </script> inside inlined JS closes the enclosing tag early and dumps the rest of the
  // module into the document as text. Silent, and it would break the app in a way no numeric test
  // would see. Inside the app's script block this is now doubly fatal, so the check stays.
  must(!/<\/script/i.test(text), `${name} contains a literal </script> and cannot be inlined safely`);
  must(!/^\s*<!DOCTYPE/i.test(text), `${name} looks like an HTML document`);
  sources.push({ name, text });
}

if (problems.length) {
  console.error('BUILD ABORTED — the sources are not inlinable:');
  problems.forEach(p => console.error('  ' + p));
  console.error('\nNothing was written. index.html is unchanged.');
  process.exitCode = 1;
  return;
}

/* --- compose the block ----------------------------------------------------------------- */
const stamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
let block = `${BEGIN}\n`;
block += `/* Generated ${stamp}Z from ${sources.map(s => s.name).join(', ')}${skipped.length ? ' [without: ' + skipped.join(', ') + ']' : ''} — ${sources.reduce((n, s) => n + s.text.length, 0)} bytes of module source. */\n`;
for (const s of sources) {
  const sha = crypto.createHash('sha256').update(s.text, 'utf8').digest('hex').slice(0, 12);
  block += `\n/* ===== ${s.name}  sha256:${sha} ===== */\n`;
  block += s.text.replace(/\s*$/, '') + '\n';
}
block += `${END}`;

/* --- splice into index.html ------------------------------------------------------------- */
const html = fs.readFileSync(TARGET, 'utf8');
must(html.length > 100000, 'index.html is implausibly small — wrong file?');

/* One-time migration: strip the legacy <script>-wrapped region, including the tags that wrapped it. */
let base = html, migrated = false;
const ob = base.indexOf(OLD_BEGIN);
if (ob >= 0) {
  const oe = base.indexOf(OLD_END, ob);
  must(oe > ob, 'the legacy BEGIN marker is present but no legacy END marker follows it');
  let s = ob, e = oe + OLD_END.length;
  const before = base.slice(0, ob), ls = before.lastIndexOf('<script>');
  if (ls >= 0 && before.slice(ls).trim() === '<script>') s = ls;      // swallow the opening tag
  const after = base.slice(e);
  const cm = after.match(/^\s*<\/script>/);
  if (cm) e += cm[0].length;                                          // and the closing tag
  base = base.slice(0, s) + base.slice(e);
  migrated = true;
}

let out, mode;
const b = base.indexOf(BEGIN);
if (b >= 0) {
  const e = base.indexOf(END, b);
  must(e > b, 'the BEGIN marker is present but no END marker follows it — refusing to guess the region');
  out = base.slice(0, b) + block + base.slice(e + END.length);
  mode = 'replaced the existing marked region';
} else {
  /* Insert INSIDE the app's own script, immediately before its closing </script>. The first
     </script> in the document is the app's — there is only one, and this assertion keeps it so. */
  const close = base.indexOf('</script>');
  must(close > 0, 'no </script> found — is this really the app?');
  const open = base.indexOf('<script>');
  must(open >= 0 && open < close, 'no <script> before that </script> — refusing to guess');
  out = base.slice(0, close) + block + '\n' + base.slice(close);
  mode = migrated ? 'migrated the legacy <script>-wrapped region into the app\'s own script block'
                  : 'inserted inside the app\'s existing <script> block';
}

if (problems.length) {
  console.error('BUILD ABORTED:'); problems.forEach(p => console.error('  ' + p));
  console.error('Nothing was written.'); process.exitCode = 1; return;
}

/* --- verify by reading the result BACK, not by trusting what we just built -------------- */
const verifyFail = [];
for (const s of sources) if (out.indexOf(s.text.trim()) < 0) verifyFail.push(s.name);

must((out.match(/FORGE-3D BEGIN/g) || []).length === 1, 'the BEGIN marker does not appear exactly once');

/* THE INVARIANT THE REGRESSION GATE DEPENDS ON. Four suites read index.html with
   /<script>([\s\S]*)<\/script>\s*<\/body>/ and need exactly one script block ending at </body>.
   A second <script> tag, or any comment between </script> and </body>, makes them all report
   "no script block" and the entire gate fails. Asserted here so that no future change to this
   builder can break the gate silently. */
const nOpen = (out.match(/<script>/g) || []).length;
const nClose = (out.match(/<\/script>/g) || []).length;
must(nOpen === 1, `index.html now has ${nOpen} <script> tags — the app must have exactly one`);
must(nClose === 1, `index.html now has ${nClose} </script> tags — the app must have exactly one`);
must(/<script>[\s\S]*<\/script>\s*<\/body>/.test(out),
     "index.html no longer matches the gate's own /<script>[\\s\\S]*<\\/script>\\s*<\\/body>/ regex");
const bi = out.indexOf(BEGIN);
must(bi > 0, 'the inlined block is not where we think it is');
must(out.indexOf('<script>') < bi && bi < out.indexOf('</script>'),
     "the inlined block is NOT inside the app's single <script> block");

if (verifyFail.length) {
  console.error('VERIFY FAILED — these sources are not present verbatim after the write:', verifyFail.join(', '));
  console.error('index.html was NOT written. This check exists because a partially-inlined module would');
  console.error('still be valid JavaScript and would fail at runtime, far from the cause.');
  process.exitCode = 1;
  return;
}
if (problems.length) {
  console.error('BUILD ABORTED:'); problems.forEach(p => console.error('  ' + p));
  console.error('Nothing was written.'); process.exitCode = 1; return;
}

fs.writeFileSync(TARGET, out, 'utf8');

const grew = out.length - html.length;
console.log(`WROTE ${TARGET}`);
console.log(`  mode        : ${mode}`);
console.log(`  modules     : ${sources.map(s => s.name).join(', ')}`);
if (skipped.length) console.log(`  skipped     : ${skipped.join(', ')}`);
console.log(`  block size  : ${block.length} bytes`);
console.log(`  index.html  : ${html.length} -> ${out.length} bytes (${grew >= 0 ? '+' : ''}${grew})`);
console.log(`  verified    : every source present verbatim, one marked region, ONE script block,`);
console.log(`                inside the app's <script>, and the gate's own regex still matches`);
console.log(`\nRun the app regression gate next.`);
