/* _s3d_publish.cjs — put the 3D work where a human can actually see it.
   Publishes into a SUBDIRECTORY of the frontend dist (so the app's relative
   sw.js registration 404s and no service worker is ever installed on the host
   origin), derives the public base from `tailscale serve status` rather than
   hardcoding it, then drives the published pages in Chrome and asserts the
   3D actually rendered — a page that loads but draws nothing is the failure
   mode this exists to catch.
   Run: node _s3d_publish.cjs */
const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');

const DIST = 'C:\\Users\\Admin\\deepseek-harness\\apps\\web\\dist\\forge';
const PORT = 9363;
const sleep = ms => new Promise(r => setTimeout(r, ms));

fs.mkdirSync(DIST, { recursive: true });

/* ---------- copy the artifacts ---------- */
const copies = [
  ['_s3d_core.js', '_s3d_core.js'],
  ['_s3d_render.js', '_s3d_render.js'],
  ['_s3d_glb.js', '_s3d_glb.js'],
  ['_s3d_view.html', 's3d.html'],
  ['FORGE-3d-character.glb', 'FORGE-3d-character.glb'],
  ['FORGE-3d-filmstrip.png', 'FORGE-3d-filmstrip.png'],
  ['FORGE-3d-threeview.png', 'FORGE-3d-threeview.png']
];
copies.forEach(([from, to]) => {
  if (!fs.existsSync(from)) { console.log('  MISSING ' + from); return; }
  fs.copyFileSync(from, path.join(DIST, to));
  console.log('  ' + to.padEnd(28) + (fs.statSync(from).size / 1024).toFixed(0) + ' KB');
});

/* ---------- landing page (PNGs inlined: the host serves them as octet-stream) ---------- */
const b64 = f => fs.readFileSync(f).toString('base64');
const sheet = (f, cap) => fs.existsSync(f)
  ? '<figure><img src="data:image/png;base64,' + b64(f) + '" alt="' + cap + '"><figcaption>' + cap + '</figcaption></figure>'
  : '';

const html = `<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>FORGE 3D sandbox</title>
<style>
:root{--bg:#08090b;--card:#14161a;--line:#242830;--ink:#f2f4f7;--mut:#98a1ac;--dim:#5f6873;--volt:#cbf33a}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 Archivo,system-ui,sans-serif}
.wrap{max-width:1240px;margin:0 auto;padding:28px 20px 60px}
h1{font-size:24px;margin:0 0 6px;letter-spacing:.01em}
h1 b{color:var(--volt)}
p.lede{color:var(--mut);max-width:78ch;margin:0 0 22px}
h2{font-size:14px;letter-spacing:.08em;text-transform:uppercase;color:var(--dim);margin:34px 0 10px}
ul.facts{color:var(--mut);max-width:80ch;padding-left:20px}
ul.facts li{margin:3px 0}
ul.facts b{color:var(--ink);font-weight:700}
a.card{display:block;background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px 18px;margin:10px 0;text-decoration:none;color:var(--ink)}
a.card:hover{border-color:var(--volt)}
a.card b{display:block;font-size:16px;margin-bottom:3px}
a.card span{color:var(--mut);font-size:13.5px}
a.card em{color:var(--volt);font-style:normal;font-size:12px;font-weight:700;letter-spacing:.06em}
figure{margin:12px 0 0}
figure img{width:100%;border:1px solid var(--line);border-radius:10px;display:block;background:#0d0f13}
figcaption{color:var(--dim);font-size:12px;margin-top:6px}
code{background:#1a1d23;border:1px solid var(--line);border-radius:5px;padding:1px 5px;font-size:13px}
</style></head><body><div class="wrap">
<h1>FORGE 3D sandbox — <b>a rigged character built from scratch</b></h1>
<p class="lede">No Blender, no npm, no dependencies, no downloaded assets. The mesh, skeleton, skin
weights, inverse-kinematics solver, animation clips, renderer and glTF exporter are all generated by
about 900 lines of plain JavaScript in this folder. The bone lengths come from FORGE's own
<code>BONE</code> table, so this athlete has the same anatomy as the 2D technique demos.</p>

<a class="card" href="s3d.html"><em>INTERACTIVE</em><b>Open the live viewer &rarr;</b>
<span>Orbit with the mouse, wheel to zoom, scrub the timeline, toggle the solved skeleton, switch
clips. Needs WebGL2 — it runs on your GPU, not mine.</span></a>

<a class="card" href="FORGE-3d-character.glb" download><em>EXPORT</em><b>Download the .glb &rarr;</b>
<span>A standard glTF 2.0 binary: 21-joint skin, 20-bone skeleton, 3 animation clips at 40&nbsp;fps.
Opens in Blender, three.js, Godot, Unreal. The export is verified by re-parsing it and comparing the
decoded vertices, skin and animation keys against the engine that generated them.</span></a>

<a class="card" href="compare.html"><em>2D</em><b>The 48 technique demos, two independent sets &rarr;</b>
<span>The earlier side-by-side: the shipped demo animations next to a set authored separately, driven
by one shared engine.</span></a>

<h2>What it is</h2>
<ul class="facts">
<li><b>One welded surface</b>, not assembled primitives: the body is meshed from a signed distance
field of capsule primitives joined by a smooth-minimum union, extracted with marching
<i>tetrahedra</i> (no 256-entry tables, watertight by construction) into ~53k triangles.</li>
<li><b>Skin weights from the same field.</b> A vertex may be driven only by the body regions whose
primitives actually reach it, so an arm cannot drag the torso.</li>
<li><b>A-pose rest.</b> Arms rest 42&deg; abducted, because a hanging arm lies against the torso and
thigh and fuses with them — the reason riggers model an A-pose.</li>
<li><b>Analytic two-bone IK with a pole point</b>, so a hand or foot lands where it was authored, and
a squat keeps its feet planted exactly while the hips translate.</li>
<li><b>Poses are axis-angle rotations</b>; the right side is derived by mirroring the left across
x&nbsp;=&nbsp;0.</li>
</ul>

<h2>Rejected on purpose</h2>
<ul class="facts">
<li>No model files, no textures, no third-party media — consistent with the app's no-network,
local-first rule.</li>
<li>Blender is a <i>quality lever</i>, not a dependency: it would improve auto-weighting and give
presentation renders, but it would also move the source of truth into a binary <code>.blend</code>.
The <code>.glb</code> above is the bridge, and it is a disposable build artifact.</li>
</ul>

<h2>Motion sheets</h2>
${sheet('FORGE-3d-filmstrip.png', 'Three clips sampled across time: twist, squat (feet planted by IK), overhead reach. Volt lines are the solved skeleton.')}
${sheet('FORGE-3d-threeview.png', 'The same pose in three orthographic views — front, side, top — which is how a shape error shows up that a perspective view hides.')}
</div></body></html>`;
fs.writeFileSync(path.join(DIST, '3d.html'), html);
console.log('  3d.html                     ' + (html.length / 1024).toFixed(0) + ' KB');

/* ---------- public URL from tailscale, never hardcoded ---------- */
let base = null;
try {
  const st = execSync('tailscale serve status', { encoding: 'utf8' });
  const m = st.match(/https:\/\/[\w.-]+\.ts\.net/);
  if (m) base = m[0] + '/forge';
} catch (e) { /* tailscale not available */ }
if (!base) { console.log('\n  could not read tailscale serve status — no public URL derived'); }

/* ---------- verify what is actually served ---------- */
(async () => {
  if (!base) { process.exit(0); }
  const CHROME = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
  const chrome = spawn(CHROME, ['--headless=new', '--disable-gpu', '--enable-unsafe-swiftshader',
    '--hide-scrollbars', '--remote-debugging-port=' + PORT,
    '--user-data-dir=' + process.cwd() + '\\_gifwork\\p_s3d_pub', 'about:blank'], { stdio: 'ignore' });
  let ws = null, id = 0;
  const pending = new Map();
  const send = (m, p) => new Promise((res, rej) => {
    const n = ++id; pending.set(n, { res, rej });
    ws.send(JSON.stringify({ id: n, method: m, params: p || {} }));
  });
  try {
    for (let i = 0; i < 60; i++) {
      try {
        const list = await (await fetch('http://127.0.0.1:' + PORT + '/json/list')).json();
        const pg = list.find(t => t.type === 'page');
        if (pg) { ws = new WebSocket(pg.webSocketDebuggerUrl); break; }
      } catch (e) {}
      await sleep(250);
    }
    await new Promise(r => ws.addEventListener('open', r));
    const errors = [];
    ws.addEventListener('message', ev => {
      const m = JSON.parse(ev.data);
      if (m.id && pending.has(m.id)) {
        const p = pending.get(m.id); pending.delete(m.id);
        m.error ? p.rej(new Error(JSON.stringify(m.error))) : p.res(m.result);
      }
      if (m.method === 'Runtime.exceptionThrown') errors.push(m.params.exceptionDetails.text);
    });
    await send('Page.enable'); await send('Runtime.enable');

    const check = async (url, label, expr) => {
      errors.length = 0;
      await send('Page.navigate', { url });
      await sleep(5000);
      const r = (await send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true })).result.value;
      console.log('\n  ' + label + '  ' + url);
      console.log('    ' + JSON.stringify(r));
      if (errors.length) console.log('    PAGE ERRORS: ' + errors.slice(0, 2).join(' | '));
      return { r, errors: errors.length };
    };

    // live viewer: is the figure actually drawn on the canvas?
    const live = await check(base + '/s3d.html', 'LIVE VIEWER',
      `(function(){
         var c = document.querySelector('canvas');
         if(!c) return {err:'no canvas'};
         var t = document.createElement('canvas'); t.width=c.width; t.height=c.height;
         var g = t.getContext('2d'); g.drawImage(c,0,0);
         var d = g.getImageData(0,0,t.width,t.height).data;
         var bright=0; for(var i=0;i<d.length;i+=4){ if(d[i]>45||d[i+1]>45||d[i+2]>45) bright++; }
         return { size:c.width+'x'+c.height, brightPixels:bright, totalPixels:d.length/4,
                  pct:+(100*bright/(d.length/4)).toFixed(1), live:!!window.__LIVE_READY,
                  anims:Object.keys(window.S3D?S3D.CLIPS:{}).length };
       })()`);
    if (!live.r || !live.r.brightPixels || live.r.brightPixels < 500) console.log('    !! the 3D canvas looks EMPTY');

    // landing page: images inlined and rendering
    await check(base + '/3d.html', 'LANDING PAGE',
      `(function(){ var im=document.images; var ok=0;
         for(var i=0;i<im.length;i++) if(im[i].complete && im[i].naturalWidth>100) ok++;
         return { images:im.length, rendered:ok }; })()`);

    process.exitCode = 0;
  } catch (e) {
    console.log('  verify FAILED: ' + e.message);
    process.exitCode = 1;
  } finally {
    try { chrome.kill(); } catch (e) {}
    await sleep(800);
    try { fs.rmSync('_gifwork/p_s3d_pub', { recursive: true, force: true }); } catch (e) {}
    if (base) {
      console.log('\n  live viewer   ' + base + '/s3d.html');
      console.log('  landing page  ' + base + '/3d.html');
      console.log('  glb           ' + base + '/FORGE-3d-character.glb');
    }
    process.exit(process.exitCode || 0);
  }
})();
